In [1]:
# A simple neural network
# Tran it on a real world dataset
# Will have a lot of manual elements

In [ ]:
# 1. Load the dataset
# 2. Basic preprocessing
# 3. Training process -> create the model, forward pass, loss calculation, backprop, parameters update
# 4. Model evaluation

In [4]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [8]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [9]:
X_train,X_test,y_train,y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,)

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
X_train

array([[ 0.96640771, -0.98524847,  0.93070381, ...,  0.45776479,
        -0.24569195, -0.28416608],
       [-1.19961173, -0.29283177, -1.12414766, ..., -0.24503768,
        -0.46689448,  1.77263451],
       [ 2.64474785,  1.13570899,  2.5656154 , ...,  1.41448299,
        -0.49960753, -0.38475535],
       ...,
       [ 3.94447254, -0.19851587,  3.92736221, ...,  0.66784983,
        -1.97169479, -1.61461207],
       [-0.72040889, -0.22382014, -0.74579406, ..., -0.49018728,
         0.46153303, -0.31528762],
       [-1.2075231 , -0.4745624 , -1.19264271, ..., -0.89826613,
         0.11726713, -0.58371093]], shape=(455, 30))

In [12]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [14]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
# Defining the model
class MySimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self,X):
        z=torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    def  loss_function(self,y_pred,y):
        # Clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred, epsilon, 1-epsilon)

        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [17]:
learning_rate=0.1
epochs=25

In [26]:
# Training pipeline
# create model
model=MySimpleNN(X_train_tensor)

for epoch in range(epochs):
    # forward pass
    y_pred=model.forward(X_train_tensor)
    print(y_pred)
    # loss calculation
    loss=model.loss_function(y_pred,y_train_tensor)
    
    # backward pass
    loss.backward()
    # parameters update
    with torch.no_grad():
        model.weights -=learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad
    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

tensor([[7.2698e-01],
        [1.0000e+00],
        [1.0000e+00],
        [1.8239e-03],
        [9.9967e-01],
        [2.6444e-01],
        [1.2508e-01],
        [1.3646e-05],
        [9.8407e-01],
        [9.9985e-01],
        [9.9960e-01],
        [2.7883e-04],
        [4.0565e-03],
        [9.8789e-01],
        [4.2543e-03],
        [1.4581e-05],
        [9.9973e-01],
        [8.8219e-04],
        [9.5748e-01],
        [9.9998e-01],
        [1.0466e-03],
        [9.9948e-01],
        [2.0595e-04],
        [3.1398e-06],
        [1.1686e-04],
        [8.9046e-01],
        [3.2843e-04],
        [2.7900e-01],
        [5.1222e-04],
        [1.0000e+00],
        [9.3418e-01],
        [8.1289e-03],
        [2.3156e-04],
        [2.8439e-02],
        [2.5823e-04],
        [4.4621e-03],
        [1.5816e-04],
        [9.9953e-01],
        [6.8893e-04],
        [6.9652e-05],
        [1.0000e+00],
        [9.9854e-01],
        [7.3960e-08],
        [7.8257e-06],
        [1.0314e-05],
        [4.7224e-03],
        [1.0766e-05],
        [1.9436e-04],
        [1.6491e-07],
        [5.2989e-01],
        [1.0000e+00],
        [1.4892e-05],
        [3.0559e-02],
        [2.3735e-06],
        [9.9190e-01],
        [1.0000e+00],
        [8.2021e-01],
        [2.0676e-02],
        [1.9632e-01],
        [7.8941e-03],
        [1.0000e+00],
        [6.6031e-01],
        [9.9999e-01],
        [1.9549e-03],
        [8.2173e-03],
        [7.0889e-05],
        [1.3862e-05],
        [9.7034e-04],
        [1.8597e-08],
        [9.9640e-01],
        [1.0000e+00],
        [3.0879e-04],
        [1.0000e+00],
        [1.0000e+00],
        [9.9764e-01],
        [1.7968e-04],
        [9.9831e-01],
        [6.3459e-01],
        [5.7044e-05],
        [1.0000e+00],
        [1.0000e+00],
        [9.2592e-01],
        [2.9605e-06],
        [1.0000e+00],
        [1.3849e-06],
        [3.0158e-04],
        [9.9999e-01],
        [6.6149e-06],
        [1.0000e+00],
        [2.6996e-07],
        [9.9995e-01],
        [3.0876e-03],
        [4.9313e-03],
        [1.0000e+00],
        [5.8076e-06],
        [1.0000e+00],
        [1.7722e-04],
        [1.0000e+00],
        [7.5167e-05],
        [1.0000e+00],
        [1.1343e-06],
        [7.7639e-01],
        [2.3019e-06],
        [9.9969e-01],
        [2.8947e-01],
        [2.2275e-03],
        [3.1393e-05],
        [1.0000e+00],
        [1.4818e-02],
        [5.2301e-03],
        [2.7980e-05],
        [6.6252e-01],
        [6.9606e-05],
        [7.1297e-03],
        [9.0292e-04],
        [8.3486e-02],
        [1.4732e-03],
        [1.0305e-04],
        [1.1660e-05],
        [2.9998e-03],
        [5.1887e-06],
        [8.7674e-01],
        [2.6170e-05],
        [8.4024e-01],
        [4.9367e-06],
        [9.9726e-01],
        [8.9917e-01],
        [1.0000e+00],
        [9.9998e-01],
        [4.1734e-03],
        [1.0000e+00],
        [1.0000e+00],
        [6.1691e-05],
        [4.6200e-02],
        [9.9374e-01],
        [9.9891e-01],
        [1.0000e+00],
        [5.1323e-01],
        [2.8121e-02],
        [1.0000e+00],
        [9.9999e-01],
        [1.0000e+00],
        [1.4628e-01],
        [4.3714e-05],
        [1.0000e+00],
        [1.0000e+00],
        [6.9717e-03],
        [9.6373e-03],
        [5.9623e-03],
        [9.4223e-01],
        [5.8599e-04],
        [6.7030e-01],
        [2.9147e-05],
        [4.4597e-01],
        [6.8604e-01],
        [1.0000e+00],
        [4.1113e-03],
        [1.2209e-03],
        [1.0000e+00],
        [1.0000e+00],
        [7.2544e-04],
        [9.6181e-05],
        [6.2234e-04],
        [1.3205e-03],
        [5.7548e-01],
        [5.9271e-02],
        [6.9521e-06],
        [3.6302e-04],
        [9.9996e-01],
        [1.0000e+00],
        [9.9965e-01],
        [2.9507e-06],
        [1.0000e+00],
        [9.9944e-01],
        [7.7583e-02],
        [1.0000e+00],
        [1.2771e-01],
        [3.6821e-01],
        [6.3861e-03],
        [9.9349e-01],
        [1.2608e-01],
        [4.3469e-03],
        [5.1024e-08],
        [1.0725e-01],
        [1.0000e+00],
        [9.9986e-01],
        [2.2151e-02],
        [1.0466e-02],
        [1.8378e-04],
        [1.0000e+00],
        [9.9997e-01],
        [6.6290e-05],
        [6.3155e-06],
        [1.0000e+00],
        [3.2129e-02],
        [9.7173e-01],
        [2.1625e-01],
        [1.0000e+00],
        [1.2743e-07],
        [1.0000e+00],
        [1.0331e-02],
        [9.9946e-01],
        [9.9973e-01],
        [9.9999e-01],
        [6.8902e-01],
        [4.8876e-01],
        [6.3219e-01],
        [6.8068e-01],
        [5.6505e-06],
        [5.5652e-07],
        [4.7712e-02],
        [1.0000e+00],
        [3.3765e-06],
        [1.6735e-05],
        [4.4322e-01],
        [3.1208e-05],
        [1.0000e+00],
        [9.2055e-01],
        [8.8215e-06],
        [1.4315e-03],
        [9.9993e-01],
        [3.8892e-02],
        [4.6301e-06],
        [8.7092e-05],
        [7.6696e-05],
        [6.6213e-02],
        [4.3921e-02],
        [8.7524e-04],
        [9.7176e-01],
        [4.0960e-05],
        [3.5471e-03],
        [7.4083e-05],
        [2.7087e-04],
        [3.8949e-04],
        [9.5474e-04],
        [2.2689e-03],
        [1.0000e+00],
        [9.9873e-01],
        [6.8444e-05],
        [9.9999e-01],
        [9.9995e-01],
        [5.1301e-06],
        [9.2404e-05],
        [1.7074e-01],
        [1.5171e-03],
        [9.2978e-01],
        [9.9999e-01],
        [1.5013e-03],
        [1.0000e+00],
        [3.7046e-02],
        [1.3673e-02],
        [1.8557e-06],
        [1.9445e-04],
        [1.0000e+00],
        [1.0057e-05],
        [7.3436e-01],
        [1.6758e-03],
        [8.2216e-01],
        [4.1001e-04],
        [9.9568e-01],
        [9.7525e-01],
        [3.7745e-05],
        [3.5404e-05],
        [7.8144e-06],
        [1.0000e+00],
        [4.8279e-01],
        [1.7844e-01],
        [9.9999e-01],
        [6.8374e-04],
        [1.4814e-02],
        [9.3604e-07],
        [5.6824e-06],
        [1.0000e+00],
        [8.2608e-03],
        [1.8258e-07],
        [9.9999e-01],
        [9.9290e-01],
        [1.4445e-03],
        [9.9999e-01],
        [1.0000e+00],
        [9.9961e-01],
        [9.9934e-01],
        [5.9984e-03],
        [1.7621e-05],
        [4.8999e-05],
        [9.3898e-03],
        [9.9789e-01],
        [8.6688e-01],
        [2.4805e-02],
        [9.1423e-05],
        [9.1834e-04],
        [1.0000e+00],
        [9.9990e-01],
        [6.1693e-03],
        [3.6334e-01],
        [1.5055e-02],
        [1.0000e+00],
        [7.4950e-07],
        [5.2668e-02],
        [9.9996e-01],
        [3.7400e-03],
        [6.3229e-04],
        [9.9249e-01],
        [1.0062e-02],
        [4.1011e-04],
        [1.1183e-04],
        [2.2919e-02],
        [3.6475e-01],
        [1.2167e-02],
        [2.4339e-03],
        [3.2296e-01],
        [6.5860e-01],
        [9.2880e-02],
        [3.4126e-04],
        [6.1564e-02],
        [8.5525e-01],
        [1.0000e+00],
        [1.0973e-04],
        [1.0000e+00],
        [9.9999e-01],
        [9.9797e-01],
        [8.6761e-01],
        [1.5833e-04],
        [4.2993e-03],
        [9.8353e-01],
        [1.0000e+00],
        [1.6898e-06],
        [2.3078e-02],
        [2.1267e-03],
        [2.2523e-02],
        [7.3017e-03],
        [2.6947e-04],
        [1.0000e+00],
        [4.6234e-01],
        [4.4265e-07],
        [2.9699e-01],
        [9.9999e-01],
        [4.4023e-01],
        [8.3838e-03],
        [3.9938e-04],
        [1.9922e-06],
        [9.3351e-01],
        [1.0000e+00],
        [1.0000e+00],
        [6.8793e-02],
        [2.8144e-01],
        [2.9303e-05],
        [8.0264e-03],
        [1.1191e-01],
        [2.2867e-04],
        [4.2471e-02],
        [6.0565e-08],
        [8.5055e-02],
        [1.2142e-04],
        [9.9912e-01],
        [7.8860e-01],
        [9.7572e-06],
        [2.6295e-04],
        [1.0000e+00],
        [4.1047e-04],
        [9.9999e-01],
        [7.9377e-04],
        [8.4550e-01],
        [3.9220e-05],
        [1.1230e-04],
        [1.7661e-02],
        [9.9551e-01],
        [1.9150e-03],
        [1.4266e-08],
        [1.0000e+00],
        [2.3980e-03],
        [6.9381e-01],
        [9.8981e-01],
        [9.9999e-01],
        [1.8067e-05],
        [3.7383e-04],
        [4.4061e-05],
        [9.9977e-01],
        [3.9318e-04],
        [1.0000e+00],
        [3.6343e-05],
        [2.0225e-02],
        [6.5086e-04],
        [1.5691e-02],
        [4.6476e-05],
        [7.2896e-05],
        [1.1559e-04],
        [1.0000e+00],
        [7.6211e-01],
        [9.9997e-01],
        [1.8407e-04],
        [2.9334e-05],
        [3.7765e-01],
        [9.9777e-03],
        [4.5281e-01],
        [5.4386e-06],
        [6.3341e-07],
        [4.2909e-01],
        [1.9733e-07],
        [9.9965e-01],
        [1.0000e+00],
        [9.9895e-01],
        [9.9221e-04],
        [1.0000e+00],
        [7.7653e-08],
        [4.1735e-06],
        [9.9994e-01],
        [1.0000e+00],
        [1.0000e+00],
        [4.3998e-04],
        [9.9999e-01],
        [8.4135e-05],
        [1.0995e-03],
        [2.7028e-06],
        [3.0763e-06],
        [1.0000e+00],
        [1.1726e-03],
        [4.7391e-02],
        [4.4825e-01],
        [6.0012e-07],
        [2.4648e-02],
        [2.3610e-01],
        [9.9481e-01],
        [8.5858e-03],
        [9.9946e-01],
        [9.9930e-01],
        [1.2767e-05],
        [9.9326e-01],
        [8.7799e-01],
        [1.0978e-03],
        [1.0000e+00],
        [9.9999e-01],
        [9.9983e-01],
        [3.8065e-03],
        [1.0000e+00],
        [3.7029e-06],
        [6.1966e-02],
        [2.4172e-03],
        [1.6522e-01],
        [9.9961e-01],
        [9.9672e-01],
        [8.9509e-01],
        [1.0000e+00],
        [2.1177e-01],
        [9.9346e-01],
        [1.0000e+00],
        [9.8911e-01],
        [9.9368e-01],
        [1.9242e-01],
        [9.9384e-01],
        [3.0619e-03],
        [8.0135e-01],
        [1.0000e+00],
        [1.8434e-04],
        [2.8027e-04]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)
Epoch: 1, Loss: 4.042975133333964
tensor([[7.0098e-01],
        [1.0000e+00],
        [1.0000e+00],
        [2.2587e-03],
        [9.9955e-01],
        [2.8520e-01],
        [1.5102e-01],
        [1.9315e-05],
        [9.7897e-01],
        [9.9982e-01],
        [9.9945e-01],
        [3.5289e-04],
        [4.8269e-03],
        [9.8478e-01],
        [5.3808e-03],
        [1.9820e-05],
        [9.9964e-01],
        [1.1004e-03],
        [9.4956e-01],
        [9.9998e-01],
        [1.2279e-03],
        [9.9927e-01],
        [2.6887e-04],
        [4.6833e-06],
        [1.7213e-04],
        [8.7766e-01],
        [4.1834e-04],
        [2.7880e-01],
        [6.1582e-04],
        [1.0000e+00],
        [9.1966e-01],
        [9.7108e-03],
        [2.8701e-04],
        [3.1760e-02],
        [3.4423e-04],
        [4.9818e-03],
        [2.3736e-04],
        [9.9949e-01],
        [9.0837e-04],
        [9.5721e-05],
        [1.0000e+00],
        [9.9816e-01],
        [1.2374e-07],
        [1.1063e-05],
        [1.4065e-05],
        [6.6007e-03],
        [1.4581e-05],
        [2.6805e-04],
        [2.7874e-07],
        [5.4599e-01],
        [1.0000e+00],
        [1.9464e-05],
        [3.4188e-02],
        [3.4547e-06],
        [9.8988e-01],
        [1.0000e+00],
        [8.3520e-01],
        [2.6148e-02],
        [2.0545e-01],
        [9.5214e-03],
        [9.9999e-01],
        [6.5988e-01],
        [9.9998e-01],
        [2.3897e-03],
        [1.0833e-02],
        [9.1784e-05],
        [1.9541e-05],
        [1.2462e-03],
        [3.1900e-08],
        [9.9499e-01],
        [1.0000e+00],
        [4.1434e-04],
        [1.0000e+00],
        [1.0000e+00],
        [9.9666e-01],
        [2.5005e-04],
        [9.9769e-01],
        [6.0505e-01],
        [7.3920e-05],
        [1.0000e+00],
        [1.0000e+00],
        [9.2064e-01],
        [4.4122e-06],
        [1.0000e+00],
        [2.4252e-06],
        [3.8914e-04],
        [9.9999e-01],
        [9.4162e-06],
        [1.0000e+00],
        [4.5356e-07],
        [9.9994e-01],
        [3.4154e-03],
        [6.2527e-03],
        [1.0000e+00],
        [8.6555e-06],
        [1.0000e+00],
        [2.1254e-04],
        [1.0000e+00],
        [1.0282e-04],
        [1.0000e+00],
        [1.7698e-06],
        [7.8877e-01],
        [3.3285e-06],
        [9.9958e-01],
        [3.1874e-01],
        [2.6309e-03],
        [4.9208e-05],
        [1.0000e+00],
        [1.8476e-02],
        [6.6501e-03],
        [4.2110e-05],
        [6.4362e-01],
        [9.7218e-05],
        [8.7312e-03],
        [1.1565e-03],
        [9.1166e-02],
        [1.6996e-03],
        [1.4062e-04],
        [1.7397e-05],
        [3.7339e-03],
        [7.3865e-06],
        [8.5501e-01],
        [3.6675e-05],
        [8.2902e-01],
        [6.3925e-06],
        [9.9633e-01],
        [8.8798e-01],
        [9.9999e-01],
        [9.9997e-01],
        [4.9495e-03],
        [1.0000e+00],
        [1.0000e+00],
        [8.4053e-05],
        [5.3398e-02],
        [9.9187e-01],
        [9.9866e-01],
        [1.0000e+00],
        [5.6899e-01],
        [3.5090e-02],
        [1.0000e+00],
        [9.9999e-01],
        [9.9999e-01],
        [1.6555e-01],
        [5.8422e-05],
        [1.0000e+00],
        [1.0000e+00],
        [9.0230e-03],
        [1.1409e-02],
        [7.1804e-03],
        [9.3531e-01],
        [7.4973e-04],
        [6.7933e-01],
        [4.2250e-05],
        [4.7528e-01],
        [7.5270e-01],
        [1.0000e+00],
        [4.4951e-03],
        [1.4669e-03],
        [1.0000e+00],
        [1.0000e+00],
        [9.5286e-04],
        [1.2679e-04],
        [7.8937e-04],
        [1.6365e-03],
        [5.3708e-01],
        [6.8522e-02],
        [1.0945e-05],
        [5.3333e-04],
        [9.9994e-01],
        [1.0000e+00],
        [9.9954e-01],
        [4.2220e-06],
        [1.0000e+00],
        [9.9929e-01],
        [9.2626e-02],
        [1.0000e+00],
        [1.4007e-01],
        [3.5891e-01],
        [7.4253e-03],
        [9.9234e-01],
        [1.5256e-01],
        [5.0490e-03],
        [8.6679e-08],
        [1.2089e-01],
        [1.0000e+00],
        [9.9980e-01],
        [2.5875e-02],
        [1.1437e-02],
        [2.4250e-04],
        [1.0000e+00],
        [9.9994e-01],
        [9.3792e-05],
        [8.7378e-06],
        [1.0000e+00],
        [3.6426e-02],
        [9.7084e-01],
        [2.1966e-01],
        [1.0000e+00],
        [2.2227e-07],
        [1.0000e+00],
        [1.0492e-02],
        [9.9926e-01],
        [9.9965e-01],
        [9.9999e-01],
        [7.0780e-01],
        [4.6251e-01],
        [6.0898e-01],
        [6.5084e-01],
        [1.0053e-05],
        [9.6556e-07],
        [5.9932e-02],
        [1.0000e+00],
        [4.9289e-06],
        [2.3191e-05],
        [4.9682e-01],
        [4.1005e-05],
        [1.0000e+00],
        [9.1202e-01],
        [1.4572e-05],
        [1.8333e-03],
        [9.9991e-01],
        [5.5342e-02],
        [6.5442e-06],
        [1.2050e-04],
        [9.9370e-05],
        [6.9744e-02],
        [4.7057e-02],
        [1.0910e-03],
        [9.7005e-01],
        [6.0974e-05],
        [4.3631e-03],
        [9.7057e-05],
        [3.6089e-04],
        [4.5574e-04],
        [1.2904e-03],
        [2.5956e-03],
        [1.0000e+00],
        [9.9815e-01],
        [9.1913e-05],
        [9.9999e-01],
        [9.9993e-01],
        [7.7647e-06],
        [1.2297e-04],
        [1.9158e-01],
        [2.1971e-03],
        [9.3027e-01],
        [9.9998e-01],
        [1.9901e-03],
        [1.0000e+00],
        [3.8818e-02],
        [1.4886e-02],
        [2.7538e-06],
        [2.7155e-04],
        [1.0000e+00],
        [1.6593e-05],
        [7.0732e-01],
        [2.0738e-03],
        [7.9407e-01],
        [5.5185e-04],
        [9.9467e-01],
        [9.7371e-01],
        [4.9087e-05],
        [5.2297e-05],
        [1.1359e-05],
        [1.0000e+00],
        [4.9752e-01],
        [1.7951e-01],
        [9.9999e-01],
        [8.9950e-04],
        [1.5477e-02],
        [1.4323e-06],
        [8.1672e-06],
        [1.0000e+00],
        [1.2153e-02],
        [2.9919e-07],
        [9.9998e-01],
        [9.9302e-01],
        [1.9410e-03],
        [9.9998e-01],
        [1.0000e+00],
        [9.9945e-01],
        [9.9912e-01],
        [6.6648e-03],
        [2.4948e-05],
        [6.6272e-05],
        [1.1374e-02],
        [9.9720e-01],
        [8.4604e-01],
        [2.8434e-02],
        [1.4047e-04],
        [1.3488e-03],
        [1.0000e+00],
        [9.9987e-01],
        [8.3869e-03],
        [4.1287e-01],
        [1.5988e-02],
        [1.0000e+00],
        [1.1658e-06],
        [6.3766e-02],
        [9.9995e-01],
        [4.4083e-03],
        [8.8842e-04],
        [9.9215e-01],
        [1.2528e-02],
        [5.8159e-04],
        [1.6620e-04],
        [2.5707e-02],
        [4.0246e-01],
        [1.4975e-02],
        [2.9721e-03],
        [3.3329e-01],
        [6.4512e-01],
        [8.7879e-02],
        [4.5904e-04],
        [6.2903e-02],
        [8.5485e-01],
        [1.0000e+00],
        [1.5608e-04],
        [1.0000e+00],
        [9.9999e-01],
        [9.9775e-01],
        [8.7107e-01],
        [1.9870e-04],
        [4.8865e-03],
        [9.8244e-01],
        [1.0000e+00],
        [2.5054e-06],
        [2.8285e-02],
        [2.8650e-03],
        [2.3425e-02],
        [8.6062e-03],
        [3.9681e-04],
        [1.0000e+00],
        [4.5775e-01],
        [6.9035e-07],
        [3.2550e-01],
        [9.9999e-01],
        [4.5682e-01],
        [1.2599e-02],
        [4.6719e-04],
        [2.9714e-06],
        [9.2624e-01],
        [1.0000e+00],
        [1.0000e+00],
        [7.8390e-02],
        [2.8393e-01],
        [4.3697e-05],
        [9.5096e-03],
        [1.1839e-01],
        [3.1748e-04],
        [5.0170e-02],
        [9.6550e-08],
        [8.7040e-02],
        [1.7140e-04],
        [9.9874e-01],
        [7.8646e-01],
        [1.3866e-05],
        [3.5361e-04],
        [1.0000e+00],
        [5.2400e-04],
        [9.9998e-01],
        [1.1126e-03],
        [8.4003e-01],
        [5.3481e-05],
        [1.5901e-04],
        [2.0844e-02],
        [9.9376e-01],
        [2.5477e-03],
        [2.4471e-08],
        [1.0000e+00],
        [3.0566e-03],
        [7.0332e-01],
        [9.8772e-01],
        [9.9998e-01],
        [2.8106e-05],
        [5.2765e-04],
        [8.0150e-05],
        [9.9968e-01],
        [4.5440e-04],
        [1.0000e+00],
        [5.1915e-05],
        [2.4487e-02],
        [9.1725e-04],
        [1.6450e-02],
        [6.4958e-05],
        [1.0495e-04],
        [1.9277e-04],
        [1.0000e+00],
        [7.4248e-01],
        [9.9997e-01],
        [2.3290e-04],
        [3.9494e-05],
        [3.8792e-01],
        [1.2436e-02],
        [4.5549e-01],
        [7.9582e-06],
        [9.4480e-07],
        [4.7825e-01],
        [3.2877e-07],
        [9.9955e-01],
        [1.0000e+00],
        [9.9864e-01],
        [1.3429e-03],
        [1.0000e+00],
        [1.2619e-07],
        [6.4578e-06],
        [9.9992e-01],
        [9.9999e-01],
        [1.0000e+00],
        [5.9535e-04],
        [9.9999e-01],
        [1.0841e-04],
        [1.3682e-03],
        [4.2340e-06],
        [4.3460e-06],
        [1.0000e+00],
        [1.4587e-03],
        [5.7667e-02],
        [4.6715e-01],
        [9.8568e-07],
        [2.7222e-02],
        [2.3561e-01],
        [9.9410e-01],
        [1.1967e-02],
        [9.9929e-01],
        [9.9904e-01],
        [1.7764e-05],
        [9.9201e-01],
        [8.6678e-01],
        [1.3385e-03],
        [1.0000e+00],
        [9.9999e-01],
        [9.9973e-01],
        [4.3698e-03],
        [1.0000e+00],
        [6.0034e-06],
        [6.6361e-02],
        [2.9018e-03],
        [1.7936e-01],
        [9.9951e-01],
        [9.9600e-01],
        [8.9944e-01],
        [1.0000e+00],
        [2.1375e-01],
        [9.9144e-01],
        [1.0000e+00],
        [9.8527e-01],
        [9.9289e-01],
        [2.0280e-01],
        [9.9200e-01],